#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figma REST API helper for watch-and-learn skill.
Creates/updates Figma files based on design data extracted from videos.

Usage:
  python figma_api.py create-frame --name "Hero" --width 1200 --height 600 --fill "#005B6E"
  python figma_api.py create-text  --content "Title" --x 100 --y 100 --size 78 --color "#000000"
  python figma_api.py get-file     --file-id <id>
  python figma_api.py list-files

Requires env var: FIGMA_TOKEN
Get token: Figma → Account Settings → Personal access tokens
"""

import os, sys, json, argparse, re
import urllib.request, urllib.error

if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

FIGMA_BASE = 'https://api.figma.com/v1'

def get_token():
    token = os.environ.get('FIGMA_TOKEN')
    if not token:
        print("ERROR: FIGMA_TOKEN env var not set.")
        print("Get token: Figma → Account Settings → Personal access tokens")
        print("Then run: $env:FIGMA_TOKEN = 'your-token'")
        sys.exit(1)
    return token

def api(method, path, body=None):
    token = get_token()
    url = f"{FIGMA_BASE}{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header('X-Figma-Token', token)
    req.add_header('Content-Type', 'application/json')
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"Figma API error {e.code}: {body}", file=sys.stderr)
        sys.exit(1)

def hex_to_rgba(hex_color, opacity=1.0):
    h = hex_color.lstrip('#')
    r, g, b = int(h[0:2],16)/255, int(h[2:4],16)/255, int(h[4:6],16)/255
    return {'r': r, 'g': g, 'b': b, 'a': opacity}

# ─── commands ─────────────────────────────────────────────────────────────────

def cmd_list_files(args):
    """List files in user's Figma drafts."""
    me = api('GET', '/me')
    print(f"Logged in as: {me.get('email', me.get('handle'))}")
    # Figma doesn't have a "list all files" endpoint without a team ID.
    # Show user info and guide.
    print("\nTo list team files, provide --team-id")
    print("To open a specific file, provide --file-id <id>")
    print("File IDs are in the URL: figma.com/file/<FILE_ID>/...")

def cmd_get_file(args):
    result = api('GET', f'/files/{args.file_id}')
    name = result.get('name', 'Unknown')
    pages = [p['name'] for p in result.get('document', {}).get('children', [])]
    print(f"File: {name}")
    print(f"Pages: {', '.join(pages)}")
    print(json.dumps(result, indent=2))

def cmd_create_frame(args):
    """
    Create a rectangle/frame node in a Figma file.
    Figma REST API doesn't support direct node creation — use Figma Plugin API for that.
    This generates a Figma plugin script instead, which the user runs in Figma.
    """
    print("NOTE: Figma REST API (v1) is read-only for nodes.")
    print("Generating Figma plugin script to run in Figma → Plugins → Development → New Plugin\n")

    fill = hex_to_rgba(args.fill) if args.fill else {'r':1,'g':1,'b':1,'a':1}
    script = f"""
// Auto-generated by watch-and-learn
// Run in Figma: Plugins → Development → Run script
const frame = figma.createFrame();
frame.name = "{args.name}";
frame.resize({args.width}, {args.height});
frame.x = {getattr(args, 'x', 0)};
frame.y = {getattr(args, 'y', 0)};
frame.fills = [{{type: 'SOLID', color: {{r: {fill['r']:.3f}, g: {fill['g']:.3f}, b: {fill['b']:.3f}}}}}];
figma.currentPage.appendChild(frame);
figma.viewport.scrollAndZoomIntoView([frame]);
console.log('Created frame: {args.name}');
"""
    print(script)
    # Save to a file for easy copy-paste
    out = 'figma_script.js'
    with open(out, 'w') as f:
        f.write(script.strip())
    print(f"\nSaved to: {out}")

def cmd_create_text(args):
    fill = hex_to_rgba(args.color) if args.color else {'r':0,'g':0,'b':0,'a':1}
    script = f"""
// Auto-generated by watch-and-learn
const text = figma.createText();
await figma.loadFontAsync({{family: "{args.font or 'Inter'}", style: "Regular"}});
text.characters = "{args.content}";
text.fontSize = {args.size or 16};
text.x = {getattr(args, 'x', 0)};
text.y = {getattr(args, 'y', 0)};
text.fills = [{{type: 'SOLID', color: {{r: {fill['r']:.3f}, g: {fill['g']:.3f}, b: {fill['b']:.3f}}}}}];
figma.currentPage.appendChild(text);
"""
    print(script)
    out = 'figma_text_script.js'
    with open(out, 'w') as f:
        f.write(script.strip())
    print(f"\nSaved to: {out}")

def cmd_build_from_spec(args):
    """
    Build a full Figma plugin script from a JSON design spec.
    Spec format:
    {
      "frames": [{"name": "Hero", "width": 1200, "height": 600, "fill": "#005B6E", "x": 0, "y": 0}],
      "texts": [{"content": "Title", "x": 100, "y": 100, "size": 78, "color": "#000000", "font": "Inter"}],
      "rectangles": [{"name": "btn", "width": 200, "height": 50, "x": 100, "y": 200, "fill": "#FFA600", "radius": 10}]
    }
    """
    with open(args.spec) as f:
        spec = json.load(f)

    lines = ['// Auto-generated by watch-and-learn', '']

    # Collect fonts needed
    fonts = set()
    for t in spec.get('texts', []):
        fonts.add(t.get('font', 'Inter'))
    for font in fonts:
        lines.append(f'await figma.loadFontAsync({{family: "{font}", style: "Regular"}});')
    lines.append('')

    for fr in spec.get('frames', []):
        fill = hex_to_rgba(fr.get('fill', '#FFFFFF'))
        lines += [
            f'const {_safe(fr["name"])} = figma.createFrame();',
            f'{_safe(fr["name"])}.name = "{fr["name"]}";',
            f'{_safe(fr["name"])}.resize({fr["width"]}, {fr["height"]});',
            f'{_safe(fr["name"])}.x = {fr.get("x",0)}; {_safe(fr["name"])}.y = {fr.get("y",0)};',
            f'{_safe(fr["name"])}.fills = [{{type:"SOLID",color:{{r:{fill["r"]:.3f},g:{fill["g"]:.3f},b:{fill["b"]:.3f}}}}}];',
            f'figma.currentPage.appendChild({_safe(fr["name"])});',
            '',
        ]

    for i, rect in enumerate(spec.get('rectangles', [])):
        fill = hex_to_rgba(rect.get('fill', '#FFFFFF'))
        vname = f'rect{i}'
        lines += [
            f'const {vname} = figma.createRectangle();',
            f'{vname}.name = "{rect.get("name", vname)}";',
            f'{vname}.resize({rect["width"]}, {rect["height"]});',
            f'{vname}.x = {rect.get("x",0)}; {vname}.y = {rect.get("y",0)};',
            f'{vname}.fills = [{{type:"SOLID",color:{{r:{fill["r"]:.3f},g:{fill["g"]:.3f},b:{fill["b"]:.3f}}}}}];',
        ]
        if rect.get('radius'):
            lines.append(f'{vname}.cornerRadius = {rect["radius"]};')
        lines += [f'figma.currentPage.appendChild({vname});', '']

    for i, t in enumerate(spec.get('texts', [])):
        fill = hex_to_rgba(t.get('color', '#000000'))
        vname = f'text{i}'
        lines += [
            f'const {vname} = figma.createText();',
            f'await figma.loadFontAsync({{family: "{t.get("font","Inter")}", style: "Regular"}});',
            f'{vname}.characters = "{t["content"]}";',
            f'{vname}.fontSize = {t.get("size", 16)};',
            f'{vname}.x = {t.get("x",0)}; {vname}.y = {t.get("y",0)};',
            f'{vname}.fills = [{{type:"SOLID",color:{{r:{fill["r"]:.3f},g:{fill["g"]:.3f},b:{fill["b"]:.3f}}}}}];',
            f'figma.currentPage.appendChild({vname});',
            '',
        ]

    lines.append('figma.viewport.scrollAndZoomIntoView(figma.currentPage.children);')
    script = '\n'.join(lines)
    print(script)
    out = args.out or 'figma_build_script.js'
    with open(out, 'w') as f:
        f.write(script)
    print(f"\nSaved to: {out}")
    print("Run in Figma: Plugins → Development → Open console, paste and run.")

def _safe(name):
    return re.sub(r'[^\w]', '_', name.lower())

# ─── CLI ──────────────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(description='Figma API helper')
    sub = p.add_subparsers(dest='cmd')

    lf = sub.add_parser('list-files')
    lf.add_argument('--team-id')

    gf = sub.add_parser('get-file')
    gf.add_argument('--file-id', required=True)

    cf = sub.add_parser('create-frame')
    cf.add_argument('--name', default='Frame')
    cf.add_argument('--width', type=int, default=1200)
    cf.add_argument('--height', type=int, default=600)
    cf.add_argument('--fill', default='#FFFFFF')
    cf.add_argument('--x', type=int, default=0)
    cf.add_argument('--y', type=int, default=0)

    ct = sub.add_parser('create-text')
    ct.add_argument('--content', required=True)
    ct.add_argument('--x', type=int, default=0)
    ct.add_argument('--y', type=int, default=0)
    ct.add_argument('--size', type=int, default=16)
    ct.add_argument('--color', default='#000000')
    ct.add_argument('--font', default='Inter')

    bs = sub.add_parser('build-from-spec')
    bs.add_argument('--spec', required=True, help='Path to JSON spec file')
    bs.add_argument('--out', default=None)

    args = p.parse_args()
    if args.cmd == 'list-files':     cmd_list_files(args)
    elif args.cmd == 'get-file':     cmd_get_file(args)
    elif args.cmd == 'create-frame': cmd_create_frame(args)
    elif args.cmd == 'create-text':  cmd_create_text(args)
    elif args.cmd == 'build-from-spec': cmd_build_from_spec(args)
    else: p.print_help()

if __name__ == '__main__':
    main()
